language: generic
sudo: required
services:
  - docker

before_install: #before test run
  - docker build -t krstncreyes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krstncreyes/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2" #region of elastic beanstalk
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-674998075297" #S3 bucket that holds all files
  bucket_path: "docker-react" #same as app name
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY